### ISSUE TITLE
Checklist for February 20th Event

### ISSUE THREAD

**Issue by Fauntleroy** [nodeschool/oakland#20]
Here's a checklist of things I need to remember to do for the next event:

##### Event checklist

- [x] Confirm date and time with venue
- [x] Print stickers
- [x] Wrangle mentors
- [x] Create ti.to event
- [x] Update website
- [x] Add event to nodeschool.io calendar
- [x] Promote event on Twitter
- [ ] Ask mentors to help promote
- [ ] Reach out to potential promotion partners
- [x] Deliver list of attendees to venue
- [ ] Get nametags, snacks, supplies
- [ ] Pre-event confirmation with venue host (day before & day of).
- [ ] Get guest WiFi credentials

##### Day of Event

- [x] Send out social media reminders about event
- [x] Arrive early and ensure everything is in order
- [ ] Set up check in/greet/sticker area
- [x] Set up refreshments
- [ ] Put up wayfinding signs
- [x] Give opening speech
- [x] Order Pizza
- [x] Take group photo
- [x] Clean up event
- [x] Mentor appreciation happy hour :beers:
